package com.qa.calculator;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class CalculatorTest {
	private Calculator calculator;
	@Before
	public void setup() {
		calculator= new Calculator();
		
	}
	@Test
	public void MultiplyTestWithTwoTwo() {
		Calculator calculator = new Calculator();
		calculator.multiply(3,2);
		assertEquals(4, calculator.multiply(2, 2));

	}
	@Test
	public void MultiplyTestWithThreeTwo() {
		Calculator calculator = new Calculator();
		calculator.multiply(3,2);
		assertEquals(6, calculator.multiply(3, 2));
}
	@Test
	public void DivideTestWithTwoTwo() {
		Calculator calculator = new Calculator();
		calculator.divide(2,2);
		assertEquals(1.0, calculator.divide(2, 2));
		} 
	
	@Test(expected = ArithmeticException.class)
	public void DivideByZero() {
		Calculator calc= new Calculator();
		calc.divide(5,0);
	}
	public void DivideTestWithThreeTwo() {
		Calculator calculator = new Calculator();
		calculator.divide(3,2);
		assertEquals(2, calculator.divide(4, 2));
	}
	
	@Test
	public void AddTestWithTwoTwo() {
		Calculator calculator = new Calculator();
		calculator.add(2,2);
		assertEquals(4, calculator.add(2, 2));
}
	@Test
	public void AddTestWithThreeTwo() {
		Calculator calculator = new Calculator();
		calculator.add(3,2);
		assertEquals(4, calculator.add(3, 2));
		}
	@Test
	public void SubstractTestWithTwoTwo() {
		Calculator calculator = new Calculator();
		calculator.substract(2,2);
		assertEquals(40, calculator.substract(2, 2));
	}
		@Test
		public void SubstractTestWithThreeTwo() {
			Calculator calculator = new Calculator();
			calculator.substract(3,2);
			assertEquals(1, calculator.substract(3, 2));
		}}


